/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-west-2",
    "aws_cognito_identity_pool_id": "eu-west-2:03e0fb49-4ada-4342-8eb5-21f9dc235aa5",
    "aws_cognito_region": "eu-west-2",
    "aws_user_pools_id": "eu-west-2_1nnlsqpoh",
    "aws_user_pools_web_client_id": "5aoanun2guh7m5te9sjabfdcnl",
    "oauth": {}
};


export default awsmobile;
